### ISSUE TITLE
UI & UX optimization (20241219)

### ISSUE THREAD

**Issue by ourai** [openbuildxyz/openbuild-frontend#1]
There are some UI & UX related optimization points which are very friendly to newcomers! 😄

- [x] Reduce strange white spaces in the header nav menu.
    <img width="360" alt="image" src="https://github.com/user-attachments/assets/c5097378-1013-467f-840f-4efbf6813636">
- [x] Remove the text color transparency of the introduction part in course or challenge details page.
    <img alt="image" src="https://github.com/user-attachments/assets/780a9038-438f-4b3e-8636-ccaf1860231e">
- [x] Some selects as filter condition don't need to be searchable.
    <img width="597" alt="image" src="https://github.com/user-attachments/assets/2552acf0-d138-4700-8663-401e22222ca7">
    <img width="397" alt="image" src="https://github.com/user-attachments/assets/597480ed-47b1-4a55-9cc2-d8bb4f823122">

    They could be located in:
    - [x] "Sorts" condition select in <https://openbuild.xyz/learn/challenges>
    - [x] "Language" and "Sorts" condition selects in <https://openbuild.xyz/learn/courses>
    - [x] "Sorts" condition select in <https://openbuild.xyz/learn/career_path>
    - [x] "Sorts" condition select in <https://openbuild.xyz/bounties>
    - [x] "Experience" and "Sort by" condition selects in <https://openbuild.xyz/shilling>

**Comment by oreilia** [comment]
:-)

**Comment by Yolo-00** [comment]
@ourai 12/19-12/20

**Comment by Yolo-00** [comment]
> 减少标题导航菜单中奇怪的空白。
 是想要什么效果呢，宽度加大还是？

**Comment by ourai** [comment]
> > 减少标题导航菜单中奇怪的空白。
> 
> 是想要什么效果呢，宽度加大还是？

就是一段英文自动换行的问题，让它在自动换行时距离右侧边界不要有那么多空白部分，并且同时要保证单词的完整性。
