### ISSUE TITLE
开发指南推荐用pnpm，为啥项目里是yarn.lock

### ISSUE THREAD

**Issue by wiirhan** [openbuildxyz/openbuild-frontend#21]
![image](https://github.com/user-attachments/assets/987f34fa-fe15-4253-bf33-4b91760463af)

**Comment by ourai** [comment]
本地开发时用哪个都不影响，项目也没用到什么非 pnpm 不可的特性，所以 pnpm 只是「推荐」而非「必须」。

`yarn.lock` 是我接手前的遗留文件，为避免影响线上版本构建就暂时没删掉，我会找时间专门处理这个问题，把它删掉。
