### ISSUE TITLE
首页 STEP2 跳转路由undefined，并且点击不同开发者跳转的路径都是一样的

### ISSUE THREAD

**Issue by wiirhan** [openbuildxyz/openbuild-frontend#38]
![image](https://github.com/user-attachments/assets/1229219b-68d3-403a-a6fb-6ae88cf63d1d)
![image](https://github.com/user-attachments/assets/5da5e69d-fb95-4cbe-b6cd-521a877f93b1)

这里有两个问题：
1. 数据undefined
2. a标签没有做事件冒泡处理，导致跳转的其实是上层地址

**Comment by ourai** [comment]
链接跳转应该没问题，刚才我正好试过。但 `<a>` 内嵌套 `<a>` 是个问题。

**Comment by wiirhan** [comment]
> 链接跳转应该没问题，刚才我正好试过。但 `<a>` 内嵌套 `<a>` 是个问题。

嵌套的问题我改了，改的时候发现链接跳转有问题。改完之后点击a标签会跳转到http://localhost:3000/u/undefined
![image](https://github.com/user-attachments/assets/861aeeb7-e349-4539-93d7-0758d7b8412e)

**Comment by ourai** [comment]
> > 链接跳转应该没问题，刚才我正好试过。但 `<a>` 内嵌套 `<a>` 是个问题。
> 
> 嵌套的问题我改了，改的时候发现链接跳转有问题。改完之后点击a标签会跳转到http://localhost:3000/u/undefined ![image](https://private-user-images.githubusercontent.com/19991141/398973783-861aeeb7-e349-4539-93d7-0758d7b8412e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzUzNjE0NzEsIm5iZiI6MTczNTM2MTE3MSwicGF0aCI6Ii8xOTk5MTE0MS8zOTg5NzM3ODMtODYxYWVlYjctZTM0OS00NTM5LTkzZDctMDc1OGQ3Yjg0MTJlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMjglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjI4VDA0NDYxMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTc0Zjk0NmI3YTU3YzVhOWFkYWNjZWViNjkzMWM1ZmYzMjFmMjIyNGMwZmZiOWRjM2IzMmZjMjdlMjYwMzliMzcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.nPVVhq-d1dp9y4IZ2fKOnYr0rBHka1vxnynRqu0Mu18)

@zhang-wenchao 接口 `ts/v1/index` 返回的数据里，`items.community` 里的 `users` 缺少 `user_handle` 这个在前端读取的字段。
